---
title: "About me"
menu: "main"
disable_comments: true
nodateline: true
output:
  html_document:
    keep_md: TRUE
---

Hi, I'm Raj, a data scientist. I help organisations use data to make well informed business decisions.

In June 2017, I joined the C1X team as a data scientist. Currently I'm working on building a category reporting system for a large ecommerce client. 

Previously I have:

1. Enabled data access to the entire organization by setting up Apache Superset and Metabase. This helped folks access reports in a self-service manner using industry-leading tools. Allowing easy access to rich reports is truly a game-changer in any organization

2. Developed a URL classification model to identify and enrich an ad impression to provide more context for campaign selection

3. AWS cost optimisation by developing a routing model to match ad impressions with bidders. 

4. Identifying top monetisation friendly users based on various buying intents. This helped us identify which publisher had a premium audience and made us focus more of our efforts on growing those accounts. 

Outside all this, I love cooking, bit of poetry and morning walks. 

I've lived in Bengaluru(India) since 2017 but grew up in New Delhi (India).

